language: ruby
sudo: false
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.5.3
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
env:
  - BOOKINGSYNC_URL=https://www.bookingsync.com
script: "bundle exec rake spec"
