language: ruby
sudo: false
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.3.3
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
env:
  - BOOKINGSYNC_URL=https://www.bookingsync.com
script: "bundle exec rake spec"
